v2.3.11 (#926)
* cache build

* Catch and disable MQTT on name resolution error

* Doorbell quick response

* Set camera time zone #916

* Set timezone on camera #916

* OSD toggle for logo/timestamp

* Add K10006 auth #742

* Fix /time_zone/get and return offset #916

* convert TZ offset to hours #916

* custom video filter #919

* Resend discovery message on HA online #907 #920

* Revert K10006 for WYZEDB3 #742

* Add more MQTT entities #921 #922

* Return json response/value for commands #835

* Fix threading issue on restart #902

* Fix SET cruise_points over MQTT

* SET cruise_point #835

* split into multiple jobs

* changelog

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -12,11 +12,26 @@ on:
   workflow_dispatch:
 
 jobs:
+  prebuild:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Should build?
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "The DOCKERHUB_USERNAME secret is missing."
+            exit 1
+          fi
+
   build:
+    needs: [prebuild]
     runs-on: ubuntu-latest
     permissions:
       contents: write
       packages: write
+
+    strategy:
+      matrix:
+        dockerfile: ['multiarch', 'hwaccel', 'qsv']
 
     steps:
       - name: Checkout repository
@@ -38,8 +53,6 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      # Login against a Docker registry except on PR
-      # https://github.com/docker/login-action
       - name: Log into registry ghcr.io
         if: github.event_name != 'pull_request'
         uses: docker/login-action@v2
@@ -48,8 +61,13 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      # Extract metadata (tags, labels) for Docker
-      # https://github.com/docker/metadata-action
+      - name: matrix image type
+        id: image_type
+        run: |
+          echo "suffix=${{ matrix.dockerfile == 'hwaccel' && '-hw' || matrix.dockerfile == 'qsv' && '-qsv' ||'' }}" >> $GITHUB_OUTPUT
+          echo "platforms=${{ matrix.dockerfile == 'multiarch' && 'linux/amd64,linux/arm64,linux/arm' || 'linux/amd64' }}" >> $GITHUB_OUTPUT
+          echo "arch=${{ matrix.dockerfile == 'multiarch' && 'amd64,armhf,aarch64' || 'amd64' }}" >> $GITHUB_OUTPUT
+
       - name: Extract Docker metadata
         id: meta
         uses: docker/metadata-action@v4
@@ -57,65 +75,34 @@ jobs:
           images: |
             ${{ github.repository_owner }}/wyze-bridge
             ghcr.io/${{ github.repository }}
-          tags: |
-            type=schedule
-            type=semver,pattern={{ version }}
-            type=edge,branch=main,enable=${{ github.event_name == 'push' }}
-            type=ref,event=branch,enable=${{ contains(github.ref,'dev') }}
-
-      # Extract metadata (tags, labels) for Docker
-      # https://github.com/docker/metadata-action
-      - name: Extract Docker metadata for hwaccel builds
-        id: hwmeta
-        uses: docker/metadata-action@v4
-        with:
-          images: |
-            ${{ github.repository_owner }}/wyze-bridge
-            ghcr.io/${{ github.repository }}
           flavor: |
             latest=auto
-            suffix=-hw,onlatest=true
+            suffix=${{ steps.image_type.outputs.suffix }},onlatest=true
           tags: |
-            type=schedule,suffix=-hw
-            type=semver,pattern={{ version }},suffix=-hw
-            type=edge,branch=main,enable=${{ github.event_name == 'push' }},suffix=-hw
-            type=ref,event=branch,enable=${{ contains(github.ref,'dev') }},suffix=-hw
-
-      - name: Extract Docker metadata for qsv builds
-        id: qsvmeta
-        uses: docker/metadata-action@v4
-        with:
-          images: |
-            ${{ github.repository_owner }}/wyze-bridge
-            ghcr.io/${{ github.repository }}
-          flavor: |
-            latest=auto
-            suffix=-qsv,onlatest=true
-          tags: |
-            type=schedule,suffix=-qsv
-            type=semver,pattern={{ version }},suffix=-qsv
-            type=edge,branch=main,enable=${{ github.event_name == 'push' }},suffix=-qsv
-            type=ref,event=branch,enable=${{ contains(github.ref,'dev') }},suffix=-qsv
+            type=schedule,suffix=${{ steps.image_type.outputs.suffix }}
+            type=semver,pattern={{ version }},suffix=${{ steps.image_type.outputs.suffix }}
+            type=edge,branch=main,enable=${{ github.event_name == 'push' }},suffix=${{ steps.image_type.outputs.suffix }}
+            type=ref,event=branch,enable=${{ contains(github.ref,'dev') }},suffix=${{ steps.image_type.outputs.suffix }}
 
       - name: Update Release Version
-        if: steps.meta.outputs.VERSION != ''
+        id: version_bump
+        if: startsWith(github.ref, 'refs/tags/v')
         run: |
-          if [[ ${{ steps.meta.outputs.VERSION }} =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]; then
-            sed -i "s/^VERSION=.*/VERSION=${{ steps.meta.outputs.VERSION }}/" ./app/.env
-            jq --arg VERSION "${{ steps.meta.outputs.VERSION }}" '.version = $VERSION' ./app/config.json > updated.json
+          TAG_NAME=${GITHUB_REF##*/v}
+          if [[ $TAG_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]; then
+            sed -i "s/^VERSION=.*/VERSION=${TAG_NAME}/" ./app/.env
+            jq --arg VERSION "${TAG_NAME}" '.version = $VERSION' ./app/config.json > updated.json
             mv updated.json ./app/config.json
           fi
 
-      # Build and push Docker image with Buildx (don't push on PR)
-      # https://github.com/docker/build-push-action
-      - name: Build and push a multi-arch Docker image
+      - name: Build and push a Docker image
         uses: docker/build-push-action@v4
         with:
           builder: ${{ steps.buildx.outputs.name }}
           context: ./app/
           push: ${{ github.event_name != 'pull_request' }}
-          file: ./app/Dockerfile.multiarch
-          platforms: linux/amd64,linux/arm64,linux/arm
+          file: ./app/Dockerfile.${{ matrix.dockerfile }}
+          platforms: ${{ steps.image_type.outputs.platforms }}
           build-args: BUILD=${{ steps.meta.outputs.VERSION }}
           labels: |
             ${{ steps.meta.outputs.labels }}
@@ -123,51 +110,30 @@ jobs:
             io.hass.description=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.description'] }}
             io.hass.version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
             io.hass.type=addon
-            io.hass.arch=amd64,armhf,aarch64
+            io.hass.arch=${{ steps.image_type.outputs.arch }}
           tags: ${{ steps.meta.outputs.tags }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
 
-      # Build and push Docker image with Buildx (don't push on PR)
-      # https://github.com/docker/build-push-action
-      - name: Build and push an amd64 Docker image with hwaccel enabled
-        uses: docker/build-push-action@v4
-        with:
-          builder: ${{ steps.buildx.outputs.name }}
-          context: ./app/
-          push: ${{ github.event_name != 'pull_request' }}
-          file: ./app/Dockerfile.hwaccel
-          platforms: linux/amd64
-          build-args: BUILD=${{ steps.meta.outputs.VERSION }}
-          labels: |
-            ${{ steps.meta.outputs.labels }}
-            io.hass.name=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.title'] }}
-            io.hass.description=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.description'] }}
-            io.hass.version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
-            io.hass.type=addon
-            io.hass.arch=amd64
-          tags: ${{ steps.hwmeta.outputs.tags }}
-
-      - name: Build and push an amd64 Docker image with QSV drivers
-        uses: docker/build-push-action@v4
-        with:
-          builder: ${{ steps.buildx.outputs.name }}
-          context: ./app/
-          push: ${{ github.event_name != 'pull_request' }}
-          file: ./app/Dockerfile.hwaccel
-          build-args: |
-            BUILD=${{ steps.meta.outputs.VERSION }}
-            QSV=1
-          labels: |
-            ${{ steps.meta.outputs.labels }}
-            io.hass.name=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.title'] }}
-            io.hass.description=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.description'] }}
-            io.hass.version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
-            io.hass.type=addon
-            io.hass.arch=amd64
-          tags: ${{ steps.qsvmeta.outputs.tags }}
-
+  version_bump:
+    needs: [build]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Update Release Version
+        id: version_bump
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          TAG_NAME=${GITHUB_REF##*/v}
+          if [[ $TAG_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]; then
+            sed -i "s/^VERSION=.*/VERSION=${TAG_NAME}/" ./app/.env
+            jq --arg VERSION "${TAG_NAME}" '.version = $VERSION' ./app/config.json > updated.json
+            mv updated.json ./app/config.json
+            echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
+          fi
       - name: Commit and push changes
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
           branch: main
-          commit_message: 'Bump Version to v${{ steps.meta.outputs.VERSION }}'
+          commit_message: 'Bump Version to v${{ steps.version_bump.outputs.tag }}'
           file_pattern: 'app/.env app/config.json'
